### PR TITLE
Update EspoCRM 8.0.2 for TKL18

### PR DESCRIPTION
**Pull request by UncleDan**

### CODE REVIEW

**Review by Christie018 — CHANGES_REQUESTED** [review]
Code changes to update this appliance look good to me. Additionally, code changes are documented in the changelog. The only suggestion I would have is to consider the related [tracker issue](https://github.com/turnkeylinux/tracker/issues/511) to update the appliance's README.md file. Please let me know if you'd like any assistance on this. 
Once this is done, the app looks ready for testing 👍🏾

**Comment by UncleDan** [comment]
@Christie018 it seems to me it was already done (info are there and I did not add anything, just checked the links).

> Installed from upstream source code to /var/www/espocrm

> Security note: Updates to EspoCRM may require supervision so they ARE NOT configured to install automatically. See EspoCRM documentation for upgrading.

Basically I just tested the build and checked the links as noted here https://github.com/UncleDan/turnkeylinux-apps-test-18

**Comment by Christie018** [comment]
Thanks for taking a sec to look into this for me. I've gone through and updated our collaboration platforms to note that I've reviewed and approved this appliance's code changes. Additionally, I've gone through and updated the related tracker issue to show that this appliance has been remediated.

**Comment by a3s7p** [comment]
Affected by https://github.com/turnkeylinux/common/pull/283 which is now fixed & merged.

EspoCRM version needs to be bumped to 8.0.6 which is currently latest:

```
diff --git a/changelog b/changelog
index 9675181..def25ef 100644
--- a/changelog
+++ b/changelog
@@ -1,6 +1,6 @@
 turnkey-espocrm-18 (1) turnkey; urgency=low
 
-  * Install latest upstream version of EspoCRM: 7.5.5.
+  * Install latest upstream version of EspoCRM: 8.0.6.
 
   * Re-build on TurnKey Linux 18 (Debian 12 'bookworm')
 
diff --git a/conf.d/downloads b/conf.d/downloads
index 1ce1d97..fee5b6d 100755
--- a/conf.d/downloads
+++ b/conf.d/downloads
@@ -5,7 +5,7 @@ dl() {
     cd $2; curl -L -f -O $PROXY $1; cd -
 }
 
-VERSION="8.0.2"
+VERSION="8.0.6"
 URL="https://github.com/espocrm/espocrm/releases/download/$VERSION/EspoCRM-$VERSION.zip"
 
 dl $URL /usr/local/src
```

Clicksnap scenario: https://github.com/turnkeylinux/clicksnap/pull/27

Other than that LGTM.

Thank you @UncleDan!

**Pull request merged**
